package com.vms.enums;

public enum SocketEvent {
    VISITOR_CHECKED_IN,
    VISITOR_CHECKED_OUT,
    VISITOR_UPDATED,
    VISITOR_ASSIGNED_TO_PERSONNEL,

    USER_CREATED,
    PROFILE_UPDATED,
    PASSWORD_CHANGED,

    DASHBOARD_STATS_UPDATED,

    SYSTEM_MESSAGE
}
